# Generated by Django 4.2 on 2023-09-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40, verbose_name='Nombre')),
                ('ape', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('apm', models.CharField(max_length=40, verbose_name='Apellido Materno')),
                ('dir', models.TextField(null=True, verbose_name='Direccion')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto')),
            ],
        ),
    ]
